# Generated by Django 5.2.6 on 2025-09-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=64)),
                ('population_size', models.PositiveBigIntegerField()),
                ('area_in_square', models.FloatField()),
                ('capital_city', models.CharField(max_length=100)),
                ('flag', models.ImageField(upload_to='flag')),
                ('email_address', models.EmailField(max_length=254)),
                ('map', models.ImageField(upload_to='map')),
                ('website', models.URLField()),
            ],
        ),
    ]
